export const actionConstants = {
    SHOW_LOADER : 'SHOW_LOADER',
    HIDE_LOADER : 'HIDE_LOADER',
    ADD_BOOKMARK : 'ADD_BOOKMARK',
    FETCH_BOOKMARK : "FETCH_BOOKMARK",
    STORE_BOOKMARK : "STORE_BOOKMARK",
}